//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummaryCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SummaryCreator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust configurations.
        /// </summary>
        internal static string ConfigForm_AdjustConfigurations {
            get {
                return ResourceManager.GetString("ConfigForm_AdjustConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ConfigForm_Data {
            get {
                return ResourceManager.GetString("ConfigForm_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file (.xml).
        /// </summary>
        internal static string ConfigForm_MeteoSourceFile {
            get {
                return ResourceManager.GetString("ConfigForm_MeteoSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file (.xlsx).
        /// </summary>
        internal static string ConfigForm_ResultFile {
            get {
                return ResourceManager.GetString("ConfigForm_ResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row with ids.
        /// </summary>
        internal static string ConfigForm_ResultRowWithIds {
            get {
                return ResourceManager.GetString("ConfigForm_ResultRowWithIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        internal static string ConfigForm_ResultTableName {
            get {
                return ResourceManager.GetString("ConfigForm_ResultTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ConfigForm_Save {
            get {
                return ResourceManager.GetString("ConfigForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory.
        /// </summary>
        internal static string ConfigForm_SensorSourceDirectory {
            get {
                return ResourceManager.GetString("ConfigForm_SensorSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ConfigForm_Stop {
            get {
                return ResourceManager.GetString("ConfigForm_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time left.
        /// </summary>
        internal static string ConfigForm_TimeLeft {
            get {
                return ResourceManager.GetString("ConfigForm_TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Creator.
        /// </summary>
        internal static string ConfigForm_Title {
            get {
                return ResourceManager.GetString("ConfigForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ConfigPresenter_Error {
            get {
                return ResourceManager.GetString("ConfigPresenter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string ConfigPresenter_Run {
            get {
                return ResourceManager.GetString("ConfigPresenter_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation finished..
        /// </summary>
        internal static string ConfigPresenter_StatusFinished {
            get {
                return ResourceManager.GetString("ConfigPresenter_StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation is running....
        /// </summary>
        internal static string ConfigPresenter_StatusRunning {
            get {
                return ResourceManager.GetString("ConfigPresenter_StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string ConfigPresenter_StatusSaved {
            get {
                return ResourceManager.GetString("ConfigPresenter_StatusSaved", resourceCulture);
            }
        }
    }
}
